version: "1.0"
info:
  model: int-scaffold
packages:
- name: SLEDDemosProject
  gitServerName: github_prudhvi
  gitUrl: https://github.com/prudhvi-penmetsa-saggs
  gitUsername: prudhvi-penmetsa-saggs
  gitBranch: main
